 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/subscription_statuses", type: :request do
  
  # SubscriptionStatus. As you add validations to SubscriptionStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      label: 'Active'
    }
  }

  let(:invalid_attributes) {
    {
      label: nil
    }
  }

  let(:user) { create(:user) }

  before do
    get "/sessions/login/#{user.id}"
  end

  describe "GET /index" do
    it "renders a successful response" do
      SubscriptionStatus.create! valid_attributes
      get subscription_statuses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      subscription_status = SubscriptionStatus.create! valid_attributes
      get subscription_status_url(subscription_status)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_subscription_status_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      subscription_status = SubscriptionStatus.create! valid_attributes
      get edit_subscription_status_url(subscription_status)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SubscriptionStatus" do
        expect {
          post subscription_statuses_url, params: { subscription_status: valid_attributes }
        }.to change(SubscriptionStatus, :count).by(1)
      end

      it "redirects to the created subscription_status" do
        post subscription_statuses_url, params: { subscription_status: valid_attributes }
        expect(response).to redirect_to(subscription_status_url(SubscriptionStatus.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SubscriptionStatus" do
        expect {
          post subscription_statuses_url, params: { subscription_status: invalid_attributes }
        }.to change(SubscriptionStatus, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post subscription_statuses_url, params: { subscription_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          label: 'Upcoming'
        }
      }

      it "updates the requested subscription_status" do
        subscription_status = SubscriptionStatus.create! valid_attributes
        patch subscription_status_url(subscription_status), params: { subscription_status: new_attributes }
        subscription_status.reload
        expect(subscription_status.label).to eq new_attributes[:label]
      end

      it "redirects to the subscription_status" do
        subscription_status = SubscriptionStatus.create! valid_attributes
        patch subscription_status_url(subscription_status), params: { subscription_status: new_attributes }
        subscription_status.reload
        expect(response).to redirect_to(subscription_status_url(subscription_status))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        subscription_status = SubscriptionStatus.create! valid_attributes
        patch subscription_status_url(subscription_status), params: { subscription_status: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested subscription_status" do
      subscription_status = SubscriptionStatus.create! valid_attributes
      expect {
        delete subscription_status_url(subscription_status)
      }.to change(SubscriptionStatus, :count).by(-1)
    end

    it "redirects to the subscription_statuses list" do
      subscription_status = SubscriptionStatus.create! valid_attributes
      delete subscription_status_url(subscription_status)
      expect(response).to redirect_to(subscription_statuses_url)
    end
  end
end
